baseURL = 'https://zachrwong.info/'
languageCode = 'en-us'
title = 'Zach Wong'
copyright = "content © 2025 zach wong"
theme = "archie"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    subtitle = "Personal website for Zach Wong."
    mode="light"
    katex = false

[params.meta]
    favicon = true

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/mud2monarch/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://x.com/mud2monarch/"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/zachrwong/"

[taxonomies]
    tag = 'tags'

[services]
  [services.googleAnalytics]
    id = 'G-V8J51GTYGR'